name: stl builder
on: [push]
jobs:
  build-stls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install deps
        uses: py-actions/py-dependency-install@v4
        with:
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
      - name: build models
        run: for i in model_*.py; do python3 $i; done
        shell: bash
        working-directory: src